language: elixir

elixir:
  - 1.3.2

sudo: required

services:
  - docker
  - postgresql
  - redis

addons:
  postgresql: "9.5"

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/listen_test
    - HIVENT_URL=redis://localhost:6379
    - secure: "NFpAStpncQQes7n3h1xDytC78nL8v5nhWjByl99SJpRAv3VyjuvkJa95npMGSs7KDsi0570vvluNNlg4EODV6HjfN9iJLNkAZypmb3LFYC+dhPSXTT/fMX59F2QwSHiLLbFdFvgGSmCg8pkZe1zAPd+JPMr/h9MqZV5rqrZpxdH/WVN0JBYiRwZhKr2ieO7rzq3QAcVwyjQ/ziu6OwMRRWKuwG0trgnCjWE3WHviFKF8KCbJaVlj5cByGWt5U7PzW5J35+W1qrzQvs6IUOzsLhHYAhd6WWgYosCXwt354vB/2XYiO4j5EGfBa9ad2hHfH7l7ZdTtnqBbKv05MSbLKo8szuBspkuRIv3ZhxgJtTZZN9ZH2nFjAIu+i+8LRTJV0x2mylynHvW66I14YCZZ+vvA1Dk10S+9Hi/60s63zj3xALFL5CVow62sUnY94uYC1fkRk0bFs3MmP1uRtc9YQei9KG+hMSte4Cdf+nVvzSOZXRsg67LynO/iGtieArYdt5PFElZUuLot2pAyJKXjak3S7gT1joB8s+Ey1phDv6ma6yleM1evh1FsjrvTqT54uR7BjrPlbNX+mYqfjED/HrSmiPVGmPSDC76R8mJ/GLBpqbC8n/Rv12Z/dSakMfop93WMlYh3qnVkSX6zxpvypAMMOhwio0R58Rdenf1jPtE=" # DOCKER_USER
    - secure: "xqhblFwJ75FWdVqSKJDAFqPXXetAc1DUm4g/OzhY3CZhi7tRRFrG0l+gM7h18ViLnJaBbmRLnwlvWWMeiTACR7FlZ1X1zQDHoJU4WCm6oti2xiIXgCbP+bdLIFtR4behozfm0nmJCAdtsNq2Y0bvCBJNN2lWDzHdTwXPR8h0KOXS3ETcrXM+OiTouKyK8X0C9DaX46V7MJVdL5VwmvXv6YzN0D9Cdjq0T2fPdZrl1vT2WeJA6ltcNxoIAa0Ld+FXmXnCFLfZjrc+WObGtSadvVVXSj1eY2tgVEeZtfj6onX/69nlzR1ZFsAS5HNemmzQX4gOn+d69EGWaOMYeWgijAe7nFs+kaIX7PIrfpUKxI6fXX3F2L1B8bppI9gmenKM9/rW1rr7HsIwtPN8qNAmc25PnPCyu0ftFdlMqRM1LRf9xr/a2YH7GmaXUMfkb3s7C0bXuNyWSnd262r0hn7a+LAte6vuk1C7QHhymlbKTCqWxxaK4TDVc6uxMGUClUsllo2HR5R5o6JAiFgc6VELbpso4kNUTKEvPZbRYt7AdoX/8gWdvvegCVkMJjsa5D/Izhq8CLCVb4+vowtidb0bwFfD58Jjr5VlwPcHi/u1u9pr0+7wDDq5OxeF21wyDErnskCVMQ57sM9LG9U+SvNkHVq35FFK8DW60HAiDIciFq8=" # DOCKER_PASS

deploy:
  provider: script
  script: ./script/deploy.sh
  on:
    all_branches: true
